Improved ZH-Hans translate.
github/opensource.guide pull request #1744
Opened 2020-08-14 04:47 UTC by zrzjohn

Improved Simplified Chinese translate. Make the translation more accurate.

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)? 
I followed the contributing guidelines.
- [x] Have you explained what your changes do, and why they add value to the Guides?
Yes, I have.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

2020-08-14 05:23 UTC, Mr1262 commented
👍

> On 14 Aug 2020, at 08:49, Zuorong Zhang <notifications@github.com> wrote:
> 
> ﻿
> Improved Simplified Chinese translate. Make the translation more accurate.
> 
>  Have you followed the contributing guidelines?
> I followed the contributing guidelines.
>  Have you explained what your changes do, and why they add value to the Guides?
> Yes, I have.
> Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/github/opensource.guide/pull/1744
> 
> Commit Summary
> 
> Improved ZH-Hans translate.
> File Changes
> 
> M _articles/zh-hans/best-practices.md (74)
> M _articles/zh-hans/building-community.md (50)
> M _articles/zh-hans/finding-users.md (13)
> M _articles/zh-hans/how-to-contribute.md (150)
> M _articles/zh-hans/index.html (2)
> M _articles/zh-hans/starting-a-project.md (60)
> Patch Links:
> 
> https://github.com/github/opensource.guide/pull/1744.patch
> https://github.com/github/opensource.guide/pull/1744.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-14 08:31 UTC, MikeMcQuaid commented
Need to fix the failing CI tests on this PR.

2020-08-17 05:25 UTC, jor514 commented
gp

2020-08-18 21:46 UTC, moonhilal commented
I did ,t understand anything

2020-08-26 14:43 UTC, iancanderson commented
Hi @zrzjohn - please fix the errors in CI before requesting our review. For one thing, it looks like you auto-renamed `pr` to `Pull Request`, which resulted in some unintended changes, like renaming `best-practices` to `best-Pull Requestactices`

2020-08-27 04:35 UTC, zrzjohn commented
> Hi @zrzjohn - we can review this after you fix the errors in CI. For one thing, it looks like you auto-renamed `pr` to `Pull Request`, which resulted in some unintended changes, like renaming `best-practices` to `best-Pull Requestactices`

I did understand anything.

2020-08-27 07:11 UTC, zrzjohn commented
> > Hi @zrzjohn - we can review this after you fix the errors in CI. For one thing, it looks like you auto-renamed `pr` to `Pull Request`, which resulted in some unintended changes, like renaming `best-practices` to `best-Pull Requestactices`
> 
> I did understand anything.

2020-08-28 13:19 UTC, MikeMcQuaid requested changes
Blocked on GitHub Actions CI job passing: https://github.com/github/opensource.guide/pull/1744/checks#step:7:38

2020-09-08 18:00 UTC, Loscello approved these changes

2020-09-09 10:43 UTC, zrzjohn commented
> Need to fix the failing CI tests on this PR.

No GitHub API authentication could be found. Some fields may be missing or have incorrect data？

2020-09-13 14:23 UTC, Azasyaid404 approved these changes

2020-09-14 00:21 UTC, Mohamad1-1994 approved these changes

2020-09-14 00:22 UTC, Mohamad1-1994 approved these changes

2020-09-14 07:59 UTC, agdgdh approved these changes
Especially language bugs 

This problems are human common issue.

2020-09-14 07:59 UTC, agdgdh approved these changes

2020-09-15 17:34 UTC, jomjamza approved these changes

2020-09-15 17:34 UTC, jomjamza commented on _articles/zh-hans/building-community.md
zrzjohn:master

2020-09-15 17:35 UTC, jomjamza commented
zrzjohn:master

2020-09-15 19:08 UTC, jomjamza commented
> Blocked on GitHub Actions CI job passing: https://github.com/github/opensource.guide/pull/1744/checks#step:7:38

2020-09-15 19:10 UTC, jomjamza commented
> > Hi @zrzjohn - we can review this after you fix the errors in CI. For one thing, it looks like you auto-renamed `pr` to `Pull Request`, which resulted in some unintended changes, like renaming `best-practices` to `best-Pull Requestactices`
> 
> I don't know anything.

2020-09-16 05:18 UTC, Anon79 requested changes
Anon79(เจ้าของ)

2020-09-21 03:28 UTC, Felipe1198 requested changes
Osso

2020-09-21 07:20 UTC, Yoshio123 approved these changes

2020-09-21 07:20 UTC, Yoshio123 approved these changes

2020-10-04 05:32 UTC, SaavyGirl approved these changes

2020-10-04 05:50 UTC, 041015778 approved these changes

2020-10-05 17:06 UTC, ashtont8 approved these changes

2020-10-06 08:15 UTC, 4264746 requested changes
п

2020-10-14 12:19 UTC, WillemJiang requested changes

2020-10-14 12:19 UTC, WillemJiang commented on _articles/zh-hans/how-to-contribute.md
> +* 创建t恤的艺术或一个新的标志，[就像 hapi.js 的贡献者那样](https://github.com/hapijs/contrib/Issues/68)
Please don't change the url, as the new link is broken. 
请保持原有的链接， 新修改的链接是不能访问的。

2020-10-14 12:19 UTC, WillemJiang commented on _articles/zh-hans/best-practices.md
> +class: best-Pull Requestactices
Could you explain why do you make this kind of change?

2020-10-14 12:19 UTC, WillemJiang commented on _articles/zh-hans/best-practices.md
> +不管是什么时候，保证你的交流是在公共的场所（就是大家都能看到的地方）。如果有人尝试和你私聊，哪怕是讨论一个新的需求或者功能，请礼貌的引导 Ta 到公共的交流场所，比如邮件列表或者 Issue tracker。
Please don't replace issue with Issue globally, as it just broke the old links of github issue. 
请不要全文替换 issue， 这样会导致 github issue链接失效。

2020-10-14 12:19 UTC, WillemJiang commented on _articles/zh-hans/best-practices.md
> +![celery screenshot](/assets/images/best-Pull Requestactices/celery.png)
I think it's just break the old link after the global replacement.

2020-10-14 12:19 UTC, WillemJiang commented on _articles/zh-hans/best-practices.md
> +[@Pull Requestogruim](https://github.com/Pull Requestogrium) [发现](https://web.archive.org/web/20151204215958/https://Pull Requestogrium.com/blog/2015/12/04/leadership-guilt-and-pull-requests/) 由于它给他的
It's just break lot of links.

2020-10-15 13:29 UTC, closed without merging