Fa
github/opensource.guide pull request #2351
Opened 2021-04-14 11:19 UTC by silvercover

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

2021-04-14 16:38 UTC, gallexi commented
Thank you for working on this @silvercover ! I'll convert this to a draft for now while it's in progress, but feel free to convert it back when you're finished!

2021-04-24 19:08 UTC, ArtNow198 commented
> * [x]  Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> * [x]  Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2021-04-27 23:32 UTC, loida24 commented
Acces

2021-04-28 01:32 UTC, loida24 reviewed
☺️

2021-04-28 01:32 UTC, loida24 reviewed
☺️

2021-04-28 01:57 UTC, loida24 submitted a review, later dismissed

2021-04-28 04:16 UTC, NicoleAnn926 commented
Hi. Thanks for the emails and invitation to be a part of this. I have a lot of questions and I have a lot to learn about all of this. Tomorrow morning I'll go through the documents that GitHub offers to those of us who are beginners with coding. I'm clueless as to why so many people have been working on my phone. Mozilla and Google developers as well as USDA, National Science Foundation, Stacked, NIST, CIS.... I don't know what to think. Because of the many experiments logged in my phone and the death threats to be a live subject in the the entertainment business ownership of people. I've been overwhelmed with all of this and I would like to know what is going on. This hasn't exactly been a fair set-up, as I'm outnumbered and deemed the "enemy" from the other people who have focused on my life with constant contact within their own agenda for me trapped in this scandal.

2021-05-07 07:40 UTC, ErdaKamarudin commented
Code

2021-05-09 05:13 UTC, SaintPatricksCoin submitted a review, later dismissed
![1619798549686_1954324047_ca5176a7 gif](https://user-images.githubusercontent.com/63454224/117561295-87f54a00-b04a-11eb-9a2c-90b818e54f84.jpg)

2021-05-10 14:07 UTC, SaintPatricksCoin approved these changes

2021-05-10 14:40 UTC, SaintPatricksCoin submitted a review, later dismissed

2021-05-14 12:16 UTC, silvercover commented
> Thank you for working on this @silvercover ! I'll convert this to a draft for now while it's in progress, but feel free to convert it back when you're finished!

I've done the whole translation. please undo draft status. also I want to mention Farsi is RTL language and I think some tweaks and style editing needed.

2021-05-31 15:48 UTC, silvercover commented
> ☺️

Would you please review my pull request?

2021-06-16 19:53 UTC, Mohsen-Phoenix approved these changes

2021-06-21 18:13 UTC, silvercover commented
> ☺️

Would you please review my pull request?

2021-06-28 11:55 UTC, noncash15 approved these changes

2021-07-21 19:10 UTC, itsbagpack commented
Thank you for the translation work! I'll merge this when the tests pass.

2021-07-22 13:08 UTC, itsbagpack commented
@silvercover Would you mind trying to merge or rebase latest master into your PR? Hopefully the tests will get triggered by that. Thank you!

2021-07-23 11:25 UTC, silvercover commented
@itsbagpack Thanks for your help. please see this:
![Capture](https://user-images.githubusercontent.com/1590045/126775265-3c599924-3cf7-42cf-bb7b-7c202c8df3b0.JPG)

what should I do then?

2021-07-26 14:29 UTC, itsbagpack commented
@silvercover Hi, as per my earlier comments and your screenshot, the build is stuck. As such, I suggest merging latest master into your branch to hopefully kick off a new build.

2021-07-28 12:26 UTC, ghasrfakhri commented
@itsbagpack @silvercover Hi, I just merged the latest master. I hope it helps.

2021-07-28 23:44 UTC, MaryJaneLove4 approved these changes
Da

2021-07-28 23:45 UTC, MaryJaneLove4 approved these changes
Schvaleno

2021-07-28 23:46 UTC, MaryJaneLove4 approved these changes

2021-07-28 23:47 UTC, MaryJaneLove4 approved these changes
Ok

2021-07-28 23:48 UTC, MaryJaneLove4 approved these changes

2021-08-06 09:09 UTC, MaryJaneLove4 approved these changes
Cool

2021-08-07 09:37 UTC, SaintPatricksCoin approved these changes
@SaintPatricksCoin 
One Second...

![1619798549686_1954324047_ca5176a7 gif](https://user-images.githubusercontent.com/63454224/127005822-b01e9ab7-655f-48e3-bab7-ba89ba0744ea.jpg)

2021-09-07 09:48 UTC, MikeMcQuaid commented
@silvercover What's the latest status of this? Thanks!

2021-09-08 11:18 UTC, MikeMcQuaid requested changes
Awaiting CI fixes

2021-09-08 20:40 UTC, silvercover commented
> @silvercover What's the latest status of this? Thanks!

![Capture](https://user-images.githubusercontent.com/1590045/132582170-c2b51401-3550-47ad-a555-ab048afe50bf.JPG)

Hi, I get these messages and don't know what to do.

2021-09-09 09:15 UTC, MikeMcQuaid commented
@silvercover I have to manually enable CI when you push new commits. There's another error here: https://github.com/github/opensource.guide/pull/2351/checks?check_run_id=3554172773#step:7:29

2021-09-11 12:21 UTC, silvercover commented
@MikeMcQuaid 
as for [this](https://github.com/github/opensource.guide/pull/2351/checks?check_run_id=3554172773#step:7:29), we've reviewed it again and found nothing to fix.

I don't know what control characters caused this.

2021-09-12 21:11 UTC, ErdaKamarudin approved these changes

2021-09-12 22:07 UTC, MaryJaneLove4 approved these changes

2021-09-12 22:08 UTC, MaryJaneLove4 approved these changes

2021-09-12 22:08 UTC, MaryJaneLove4 approved these changes

2021-09-12 22:09 UTC, MaryJaneLove4 approved these changes

2021-09-12 22:11 UTC, jova124 commented
Jovan Ramirez

lunes, 13 de septiembre 2021, 1:09 +03:00 de MaryJaneLove4 ***@***.***>:
***@***.*** approved this pull request.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

2021-09-13 10:23 UTC, MikeMcQuaid commented
@silvercover You can push new commits now and it'll retest automatically. I'm afraid I can't merge until we figure out the failures here 😭

2021-09-14 15:36 UTC, silvercover commented
@MikeMcQuaid Hopefully I fixed few errors and warnings and now there is only 1 warning which I really don't have any clue about it in this file:
[how-to-contribute.md](https://github.com/parscoders/opensource.guide/blob/fa/_articles/fa/how-to-contribute.md)

  _`137:1-137:57  warning  Missing blank line before block node  no-missing-blank-lines  remark-lint`_

2021-09-14 15:48 UTC, MikeMcQuaid commented on _articles/fa/how-to-contribute.md
> +
```suggestion

### لازم نیست فقط روی پروژه‌های نرم‌افزاری وقت صرف کنید!

```

2021-09-14 15:49 UTC, MikeMcQuaid commented on _articles/fa/how-to-contribute.md
> +
@silvercover This should fix the CI failure you mentioned

2021-09-14 16:47 UTC, silvercover commented
@MikeMcQuaid All checks have passed!
🥳

2021-09-15 10:50 UTC, MikeMcQuaid approved these changes
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @silvercover!

2021-09-15 10:50 UTC, merged

2021-09-15 13:13 UTC, silvercover commented
@MikeMcQuaid Thank you.

Since Farsi is RTL language, what's your suggestion on making this RTL. I don't know whether putting `<div dir='rtl'>`  at the beginning allowed or not.

2021-09-15 13:23 UTC, MikeMcQuaid commented
@silvercover you're welcome!

I'd suggest something dynamic/conditional like https://github.com/github/opensourcefriday/blob/7ce1cdc59edc6840b390c2d02259878fb8c9c606/app/views/layouts/application.html.erb#L2 should be added (but will use Liquid rather than ERB). Could you open a PR for discussion?

2022-03-27 04:19 UTC, Scheusal13 reviewed
0xEa5C920973eBfff95270dd52c8045c4e6eBFc847