Russian translation
github/opensource.guide pull request #2395
Opened 2021-04-30 21:07 UTC by alroniks

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

2021-04-30 21:22 UTC, mlinksva commented
Just in case there's anything useful in them, there have been a few previous starts at Russian translations. #1299 has a couple articles translated (most of the files in that PR are still English).

2021-04-30 21:32 UTC, alroniks commented
@mlinksva Thank you for the information. I will have a look and if possible try to fetch existing translations.
I saw that it was closed due to inactivity and it is sad, but it happens in open source sometimes, unfortunately. 

I have a personal goal, during translation learn articles more carefully, so I hope my attempt will be successful. But who knows? :)

2021-05-05 17:52 UTC, mobilase commented on _data/locales/ru.yml
> +    lead: Программы с открытым кодом создаются такими же людьми, как и вы. Узнайте, как запустить и развить свой проект.
May be change "развить" to "развивать"? For me it seems more literaturaly.

2021-05-05 17:56 UTC, mobilase commented on _data/locales/ru.yml
> +      description: Узнавайте первыми о свежих заметках и советах об Open Source от GitHub.
May be change to "Узнавайте первым о свежих советах и ресурсах GitHub с открытым исходным кодом"?

2021-05-05 18:02 UTC, mobilase commented on _articles/ru/index.html
> +title: Как делать Open Source
May be change to "Как работать с открытым исходным кодом"?

2021-05-18 21:15 UTC, jaceppo approved these changes

2021-06-03 03:24 UTC, TaMaMa69 approved these changes
Bhj

2021-06-03 04:02 UTC, vuchien000 commented
Iio

2021-06-29 10:43 UTC, MaryJaneLove4 commented on _data/locales/ru.yml
> +    lead: Программы с открытым кодом создаются такими же людьми, как и вы. Узнайте, как запустить и развить свой проект.
Am lost

2021-07-07 13:48 UTC, noncash15 commented
alroniks:ru-translation

2021-07-24 11:02 UTC, pipecc approved these changes

2021-07-28 23:38 UTC, MaryJaneLove4 commented on _data/locales/ru.yml
> +      description: Узнавайте первыми о свежих заметках и советах об Open Source от GitHub.
Yes

2021-07-28 23:39 UTC, MaryJaneLove4 approved these changes

2021-07-28 23:39 UTC, MaryJaneLove4 commented on _articles/ru/index.html
> +title: Как делать Open Source
(*_*)

2021-07-28 23:40 UTC, MaryJaneLove4 commented
Czech translator

2021-07-28 23:41 UTC, MaryJaneLove4 commented
Dekuji

2021-08-06 09:02 UTC, MaryJaneLove4 approved these changes
It's right.

2021-08-06 09:03 UTC, MaryJaneLove4 commented
👍

2021-08-13 05:19 UTC, Budda0ne reviewed
[go1.16.3.src.tar.gz](https://github.com/github/opensource.guide/files/6980065/go1.16.3.src.tar.gz)

2021-08-13 09:08 UTC, oneemo95 approved these changes

2021-08-14 09:52 UTC, KashcheyMC reviewed
[](https://www.google.com/url?sa=t&source=web&rct=j&url=https://translate.google.com/%3Fhl%3Dru&ved=2ahUKEwiJ17DWnrDyAhWQO-wKHWD4CjgQFnoECBIQAg&usg=AOvVaw1GeJFpbqMHiaaRur8045v7)

2021-08-19 21:35 UTC, Aparus commented
> @mlinksva Thank you for the information. I will have a look and if possible try to fetch existing translations.
> I saw that it was closed due to inactivity and it is sad, but it happens in open source sometimes, unfortunately.
> 
> I have a personal goal, during translation learn articles more carefully, so I hope my attempt will be successful. But who knows? :)

Привет. Переводишь ещё? :-) я ещё несколько статей перевёл. В прошлый раз не разобрался как тесты запустить и т.д. Они потом добавили более подробное руководство.

2021-08-28 17:57 UTC, Mohsen-Phoenix approved these changes

2021-09-02 02:12 UTC, se7enhl approved these changes

2021-09-07 09:49 UTC, MikeMcQuaid commented
@alroniks What's the latest status here? Please try to merge `main` into your branch so CI is run. Thanks!

2021-09-07 09:58 UTC, MikeMcQuaid requested changes
Need to fix CI failures: https://github.com/github/opensource.guide/pull/2395/checks?check_run_id=3532336781#step:7:37

2021-09-15 12:02 UTC, MikeMcQuaid commented
Russian translation merged in https://github.com/github/opensource.guide/pull/2513.

2021-09-15 12:02 UTC, closed without merging