Mod.
github/opensource.guide pull request #2512
Opened 2021-08-18 04:57 UTC by Tranvanlap95

react-cropper/react-cropper

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

2021-08-18 05:41 UTC, AfirstS requested changes
Обновление и запуск, 👑🎷🎺📻📀 @AfirstSℹ️

2021-08-18 12:55 UTC, hariharanep4 commented
I could not install dependencies to run this project locally, can anyone please guide me how to do that.
Thank you in advance.

2021-08-18 17:17 UTC, closed without merging

2021-08-18 17:56 UTC, Tranvanlap95 commented
Yes i subscribe changes

Vào 0:17, Th 5, 19 thg 8, 2021 Nick Holden ***@***.***> đã
viết:

> Closed #2512 <https://github.com/github/opensource.guide/pull/2512>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/opensource.guide/pull/2512#event-5176169047>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATQ2RLS5ENSDXCEQPI34M4DT5PTKHANCNFSM5CLHDBHQ>
> .
>

2021-08-19 04:04 UTC, Witte1979 commented
Stop

Op wo 18 aug. 2021 om 19:56 schreef Tranvanlap95 ***@***.***>

> Yes i subscribe changes
>
> Vào 0:17, Th 5, 19 thg 8, 2021 Nick Holden ***@***.***> đã
> viết:
>
> > Closed #2512 <https://github.com/github/opensource.guide/pull/2512>.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/github/opensource.guide/pull/2512#event-5176169047>,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ATQ2RLS5ENSDXCEQPI34M4DT5PTKHANCNFSM5CLHDBHQ
> >
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/opensource.guide/pull/2512#issuecomment-901314601>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVHNKQ2GKSJ6MUOJ47OCRYTT5PX6JANCNFSM5CLHDBHQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-21 03:18 UTC, Anoos97 commented on index.html
> +react-cropper/react-cropper---
[dumpstate-stats.txt](https://github.com/github/opensource.guide/files/7024787/dumpstate-stats.txt)

- [ ] 

- [ ]

2021-08-21 03:19 UTC, Anoos97 reviewed
[dumpstate-stats.txt](https://github.com/github/opensource.guide/files/7024789/dumpstate-stats.txt)
index.html