Greek translation
github/opensource.guide pull request #2791
Opened 2022-04-02 19:55 UTC by ChristolisOfficial

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
With this pull request, I am aiming to provide a space for collaborators who are able to assist with translating the project into the Greek language.

2022-04-03 10:48 UTC, Mitumaru reviewed
My NFT is token change

2022-04-04 21:57 UTC, puchongcnxx29 reviewed
thanks

2022-04-05 08:56 UTC, Shahbaz9594 reviewed
Approved

2022-04-05 09:14 UTC, Mitumaru commented
> Approved

2022-04-05 21:50 UTC, Mitumaru reviewed
Okay I'm sorry

2022-04-08 11:31 UTC, Errorzim reviewed
I accept it’s

2022-04-09 15:06 UTC, Henrytech22 commented
Am good with whatever it is with BNB

2022-04-09 15:07 UTC, Henrytech22 reviewed
Good app, Bnb

2022-04-25 09:22 UTC, MikeMcQuaid requested changes
Looking good so far! Please re-request review when it's completed.

2022-04-25 12:44 UTC, Thamerhaliq reviewed
Salt

2022-04-25 16:14 UTC, ChristolisOfficial commented
> Looking good so far! Please re-request review when it's completed.

Thank you! Will do. Easter holidays are almost over here in my place so I'll get some more progress done in the next few days! 🚀

2022-04-27 00:20 UTC, paul1974nsac commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
> H

2022-04-27 00:23 UTC, paul1974nsac commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
paul1974nsac

2022-04-27 00:24 UTC, paul1974nsac commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
paul1974nsac

2022-04-27 00:28 UTC, paul1974nsac commented on _articles/el/how-to-contribute.md
> +### Improve software you rely on
> Thamer

2022-04-27 00:30 UTC, paul1974nsac commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
paul1974nsac

2022-04-27 03:23 UTC, BigsteppA1 commented
Can I review?

2022-04-28 20:03 UTC, jjjjj29 reviewed
Yy

2022-05-10 00:52 UTC, jiivii252 commented
Duit dimn duit ...

2022-05-26 12:56 UTC, Imadkhidre commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
[](url)16394374

2022-06-26 14:03 UTC, rmdanaasd commented
ممكن حد يفهمني  ويسعدني  علي البرنامج

2022-07-04 06:36 UTC, Viileeu72 commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
> 16394374

2022-07-04 06:36 UTC, Viileeu72 commented
> Can I review?

2022-07-04 06:37 UTC, Viileeu72 commented on _articles/el/how-to-contribute.md
> +## Why contribute to open source?
> 16394374

2022-07-04 06:52 UTC, GODWILLNFIRE commented
i really am a begginer and someone has stole my life and identity im really
trying to fight them off  can u teach me

On Sun, Jun 26, 2022, 8:05 AM github-actions[bot] ***@***.***>
wrote:

> This pull request has been automatically marked as stale because it has
> not had recent activity. It will be closed if no further activity occurs.
> Thank you for your contributions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/opensource.guide/pull/2791#issuecomment-1166511398>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXERJRZLNM5YTRD47OLZ23VRBBR3ANCNFSM5SLLUIXQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-07-10 01:36 UTC, Nuttapon43 reviewed
@christolis

2022-07-24 15:32 UTC, Jhstvf4t commented
I don't have money anymore to go out to the workshop, I want to eat, let alone me

2022-07-30 18:04 UTC, 1233duy reviewed
Aa

> ``

2022-08-15 13:27 UTC, MikeMcQuaid commented
Passing on this for now. @christolis please reopen when complete and passing CI, thanks!

2022-09-20 09:16 UTC, christolis commented
@MikeMcQuaid The rest of the articles have now been properly translated into the Greek language! My apologies for the massive delay! For some reason, I am unable to reopen the pull request. Should I re-create it?

2022-09-20 11:09 UTC, MikeMcQuaid commented
@christolis Reopened now! Please rebase and push to this branch.

2022-09-21 08:11 UTC, freaki2 reviewed
Approved

2022-09-21 17:01 UTC, MikeMcQuaid approved these changes
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @christolis!

2022-09-21 17:01 UTC, merged