Optimize the article according to the normal expression in Chinese.
github/opensource.guide pull request #3035
Opened 2023-06-21 06:29 UTC by dufu1991

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

2023-07-08 19:52 UTC, ahpook requested changes
I will trust that the translations are accurate; please fix the YAML header and I will merge. Thank you for these edits!

2023-07-08 19:52 UTC, ahpook commented on _articles/zh-hans/finding-users.md
> +    - building
This should not be included, it is only a 2 space indentation.

2023-07-09 01:13 UTC, dufu1991 commented
Resubmit the new PR.

2023-07-09 01:13 UTC, closed without merging

2023-09-13 07:50 UTC, Pilarm1234 reviewed
>   #@`
Duplicate of #`