Translation maintaining balance into es
github/opensource.guide pull request #3101
Opened 2023-09-20 04:30 UTC by RestrepoTorres

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

2023-09-20 04:39 UTC, bw4cnc commented
I don't understand GitHub. I don't know what to do. This like alot of of
work to understand.   Not sure what I'm suppose to do. Should I stop using
GitHub?

Blake Williamson

On Tue, Sep 19, 2023, 11:33 PM Victor Restrepo ***@***.***>
wrote:

>
>    - Have you followed the contributing guidelines
>    <https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md>?
>    - Have you explained what your changes do, and why they add value to
>    the Guides?
>
> *Please note: we will close your PR without comment if you do not check
> the boxes above and provide ALL requested information.*
> ------------------------------
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/github/opensource.guide/pull/3101
> Commit Summary
>
>    - 9893c99
>    <https://github.com/github/opensource.guide/pull/3101/commits/9893c997da4a91994b6d777111c93d7ca84a9684>
>    setup
>    - ac43b8b
>    <https://github.com/github/opensource.guide/pull/3101/commits/ac43b8b9dbd12ff0ffe9161739212215143076a3>
>    mantaining-balance header translation into spanish
>    - bd5f904
>    <https://github.com/github/opensource.guide/pull/3101/commits/bd5f90429f1f6776f8c37cf97a13a0e05f39ebee>
>    articles/es/maintaining-balance-for-open-source-maintainers.md fully
>    transalate into spanish
>    - ddea407
>    <https://github.com/github/opensource.guide/pull/3101/commits/ddea407de14dd1f18ced5b033af85b497eb014d1>
>    remove inncesary changes on the project
>    - 25cf8c4
>    <https://github.com/github/opensource.guide/pull/3101/commits/25cf8c458db3d033f974c1c36cae5da5eeac26a0>
>    articles/es/mataining-balance/ update to past tests
>
> File Changes
>
> (2 files <https://github.com/github/opensource.guide/pull/3101/files>)
>
>    - *M* Gemfile
>    <https://github.com/github/opensource.guide/pull/3101/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f>
>    (2)
>    - *A* _articles/es/maintaining-balance-for-open-source-maintainers.md
>    <https://github.com/github/opensource.guide/pull/3101/files#diff-fa08b2ac8af85fe9d6514659b9a7c421463f21fd418179209eb119a6be719570>
>    (220)
>
> Patch Links:
>
>    - https://github.com/github/opensource.guide/pull/3101.patch
>    - https://github.com/github/opensource.guide/pull/3101.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/opensource.guide/pull/3101>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4UQFGBUJWJQBG4QI53SI7TX3JW2NANCNFSM6AAAAAA47IS47I>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-09-20 04:44 UTC, bw4cnc commented
No I haven't because don't understand.

Blake Williamson

On Tue, Sep 19, 2023, 11:39 PM bw4cnc ***@***.***> wrote:

> I don't understand GitHub. I don't know what to do. This like alot of of
> work to understand. Not sure what I'm suppose to do. Should I stop using
> GitHub?
>
> Blake Williamson
>
> On Tue, Sep 19, 2023, 11:33 PM Victor Restrepo ***@***.***>
> wrote:
>
> >
> > - Have you followed the contributing guidelines
> > <https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md>?
> > - Have you explained what your changes do, and why they add value to
> > the Guides?
> >
> > *Please note: we will close your PR without comment if you do not check
> > the boxes above and provide ALL requested information.*
> > ------------------------------
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/github/opensource.guide/pull/3101
> > Commit Summary
> >
> > - 9893c99
> > <
> https://github.com/github/opensource.guide/pull/3101/commits/9893c997da4a91994b6d777111c93d7ca84a9684>
>
> > setup
> > - ac43b8b
> > <
> https://github.com/github/opensource.guide/pull/3101/commits/ac43b8b9dbd12ff0ffe9161739212215143076a3>
>
> > mantaining-balance header translation into spanish
> > - bd5f904
> > <
> https://github.com/github/opensource.guide/pull/3101/commits/bd5f90429f1f6776f8c37cf97a13a0e05f39ebee>
>
> > articles/es/maintaining-balance-for-open-source-maintainers.md fully
> > transalate into spanish
> > - ddea407
> > <
> https://github.com/github/opensource.guide/pull/3101/commits/ddea407de14dd1f18ced5b033af85b497eb014d1>
>
> > remove inncesary changes on the project
> > - 25cf8c4
> > <
> https://github.com/github/opensource.guide/pull/3101/commits/25cf8c458db3d033f974c1c36cae5da5eeac26a0>
>
> > articles/es/mataining-balance/ update to past tests
> >
> > File Changes
> >
> > (2 files <https://github.com/github/opensource.guide/pull/3101/files>)
> >
> > - *M* Gemfile
> > <
> https://github.com/github/opensource.guide/pull/3101/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f>
>
> > (2)
> > - *A* _articles/es/maintaining-balance-for-open-source-maintainers.md
> > <
> https://github.com/github/opensource.guide/pull/3101/files#diff-fa08b2ac8af85fe9d6514659b9a7c421463f21fd418179209eb119a6be719570>
>
> > (220)
> >
> > Patch Links:
> >
> > - https://github.com/github/opensource.guide/pull/3101.patch
> > - https://github.com/github/opensource.guide/pull/3101.diff
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/github/opensource.guide/pull/3101>, or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A4UQFGBUJWJQBG4QI53SI7TX3JW2NANCNFSM6AAAAAA47IS47I>
>
> > .
> > You are receiving this because you are subscribed to this thread.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/opensource.guide/pull/3101#issuecomment-1726955944>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4UQFGBM55PFV7SPKBLS2VLX3JXPVANCNFSM6AAAAAA47IS47I>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-09-22 17:35 UTC, underwoo16 requested changes
Hello, thanks for the contribution!

The translated article looks great, I am requesting that you remove changes to any other files

2023-09-22 17:35 UTC, underwoo16 commented on Gemfile
> +end
Please remove change to Gemfile

2023-09-23 04:03 UTC, closed without merging